language: node.js
node_js:
- node
services:
- postgresql
before_script:
- psql -c 'CREATE DATABASE museo_talk;' -U postgres
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: qX+GJGOeG10Kh2nsNecTlNOT42pIFldw6qc3OrE5YT0ITIGR5E3AzNvQfI62QgbVnJO8WCvz7ha13GhnsulBuGxIFnwyafH2N6udR0LhJnMEIqzjctutEO49ZlGqdrMUbbWY3gBbg9eU/Arrqa0ksftlSw/Jeq4NZ098MZq9a//MUpJ8D1Z/QN/2ahc1JR7aXkNTjFs/3BWE0mO/K/g7nyZLKbfBbuEhW/+peAtgDkjgg30Iojfg5Sb6urk2HqkscJmKHRrJ4imzGd9lGxD+RYPptaVcmlv4Tw+d7cBpI6gJXKiL0tSQonQ+iqb520CmmlbhsGeibixp5ydAHNe0WJvAaoQmH47iuSMOO3pHTC73Zz6PSCoCIBnNkAxnhp2Ei7yUi1bZ2IuvCtO54DgxST9zWml6N/h7W3LyPKCZzwwcuxTR2bCDlBN0Urc/0QTBaPWeSS120xIt8zgcvob1bSJo/Kbrt8ue6NI3Bvwzs7TinJOz7xvPUBKvdrqo3p7qU95f4if0ZEVgydP7qlkuJ7INE6TVtBkjNfFtIJY4tSd60CunzrGDygWRXezhJRQKdsiS38sHpd+j+p7ZXbqh4cJ1+PAp/eYjxviBK5bDHcoLCfgnow2fHR8hdWNXhOP9s31TmMO97JgywokjILgkhDeJxtvfUqS8ZPQAvHGLb/k=
  app: museo_talk
  skip_cleanup: true
